version: "3.4"

services:
  nginx-base:
    image: ${CONTAINER_REPO}/nginx:base
    build:
      context: ./
      target: base
      args:
        - BASE_OS=nginx:mainline-bookworm
    ports:
      - "80:80"
  nginx1:
    extends:
      service: nginx-base
    image: ${CONTAINER_REPO}/nginx:1
    build:
      target: nginx1
      args:
        APP_ENV: development
  nginx2:
    extends:
      service: nginx-base
    image: ${CONTAINER_REPO}/nginx:2
    build:
      target: nginx2
      args:
        APP_ENV: production
        BASE_OS: nginx:1.24.0-bullseye
